---
version: '3.0'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
  var_lib_unbound:
  var_log_unbound:

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - "192.168.2.150:53:53/tcp"  # IP anpassen
      - "192.168.2.150:53:53/udp"  # IP anpassen
        #- "192.168.2.150:82:80/tcp"
        #- 443:443/tcp
        #- 53:53/tcp
        #- 53:53/udp
        #- 82:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
        #- "192.168.2.150:5335:5335/tcp" # Uncomment to enable unbound access on local server
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - WEBTHEME=${WEBTHEME:-default-darker}
      - REV_SERVER=${REV_SERVER:-false}
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=unbound#53
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
      - $PWD/pihole/99-edns.conf:/etc/dnsmasq.d/99-edns.conf
      - $PWD/pihole/lighttpd-external.conf:/etc/lighttpd/external.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - frontend
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    volumes:
      - $PWD/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - $PWD/unbound/root.hints:/opt/unbound/etc/unbound/root.hints
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
    name: frontend
    external: true

networks:
  default:
    external:
      name: frontend
